kb_default(KB_FEATURE_LAYERS         ON)
kb_default(KB_FEATURE_TAPPING        ON)
kb_default(KB_FEATURE_MACROS         ON)
kb_default(KB_FEATURE_MACRO_STORE    ON)
kb_default(KB_FEATURE_MOUSEKEYS      ON)
kb_default(KB_FEATURE_CONSUMER       ON)   # the encoder maps to volume
kb_default(KB_FEATURE_BOOTMAGIC      ON)
kb_default(KB_FEATURE_DYNAMIC_KEYMAP ON)
kb_default(KB_FEATURE_ONESHOT        OFF)
kb_default(KB_FEATURE_COMBO          OFF)
kb_default(KB_FEATURE_CAPS_WORD      OFF)
kb_default(KB_FEATURE_AUTOCLICK ON)
