#!/usr/bin/env python3
"""
kle_to_layout.py — convert between keyboard-layout-editor.com and the
LAYOUT_GEOMETRY macro block in keyboards/<name>/keyboard.h.

Physical geometry is tedious and error-prone to type by hand and pleasant to
drag around in a browser, so do that instead.

FORWARD (the usual direction)
-----------------------------
  1. Lay your board out on http://www.keyboard-layout-editor.com
  2. Put the matrix position in each key's TOP-LEFT legend, as "row,col"
     (e.g. "0,0", "4,2"). This is the same convention VIA and Vial use, so an
     existing VIA layout for your board works unmodified.
  3. Copy the contents of the "Raw data" box into a file.
  4. python3 tools/keyboard/kle_to_layout.py my_layout.json

     ...and paste the printed block into keyboard.h.

REVERSE (round-tripping)
------------------------
  python3 tools/keyboard/kle_to_layout.py --to-kle keyboards/mystery6x6/keyboard.h

  Prints KLE Raw Data for the geometry already in that header. Paste it into
  keyboard-layout-editor.com's Raw data box, rearrange, and come back forward.

NOTES
-----
KLE's raw format is JSON5-ish: unquoted keys are common. This script handles
that without a JSON5 dependency. Coordinates come out in hundredths of a key
unit, which is what the firmware stores.
"""

import argparse
import json
import re
import sys


# ── KLE raw parsing ──────────────────────────────────────────────────────────

def _loads_lenient(text: str):
    """KLE's Raw Data has unquoted object keys and sometimes trailing commas.
    Quote the keys and strip the commas, then it is ordinary JSON."""
    text = text.strip()
    if not text.startswith('['):
        text = '[' + text + ']'
    # {x:1, w:2}  ->  {"x":1, "w":2}
    text = re.sub(r'([{,]\s*)([A-Za-z_][A-Za-z0-9_]*)\s*:', r'\1"\2":', text)
    text = re.sub(r',(\s*[}\]])', r'\1', text)
    return json.loads(text)


def _r100(v: float) -> int:
    """Hundredths of a key unit, rounded. KLE positions are floats."""
    return int(round(v * 100))


def parse_kle(raw):
    """KLE raw -> [dict(row, col, x, y, w, h, rot, rx, ry)] in hundredths.

    Implements the subset that matters for keyboards: per-key x/y offsets,
    w/h sizing, and r/rx/ry rotation clusters. KLE's model is a cursor that
    walks left to right and wraps at each row, with objects mutating state
    ahead of the next key."""
    keys = []
    x = y = 0.0
    w = h = 1.0
    rot = 0.0
    rx = ry = 0.0
    rot_dirty = False

    for row in raw:
        if isinstance(row, dict):
            continue                      # the metadata object KLE puts first
        if not isinstance(row, list):
            continue
        for item in row:
            if isinstance(item, dict):
                # A rotation cluster resets the cursor to (rx, ry).
                if 'r' in item:
                    rot = float(item['r']); rot_dirty = True
                if 'rx' in item:
                    rx = float(item['rx']); rot_dirty = True
                if 'ry' in item:
                    ry = float(item['ry']); rot_dirty = True
                if rot_dirty:
                    x, y = rx, ry
                    rot_dirty = False
                if 'x' in item: x += float(item['x'])
                if 'y' in item: y += float(item['y'])
                if 'w' in item: w = float(item['w'])
                if 'h' in item: h = float(item['h'])
                continue

            if not isinstance(item, str):
                continue

            legend = item.split('\n')[0].strip()
            m = re.fullmatch(r'(\d+)\s*,\s*(\d+)', legend)
            if not m:
                print(f"warning: skipping key at ({x},{y}) — top-left legend "
                      f"{legend!r} is not \"row,col\"", file=sys.stderr)
            else:
                keys.append(dict(
                    row=int(m.group(1)), col=int(m.group(2)),
                    x=_r100(x), y=_r100(y), w=_r100(w), h=_r100(h),
                    rot=int(round(rot)), rx=_r100(rx), ry=_r100(ry),
                ))
            x += w
            w = h = 1.0
        y += 1.0
        x = rx           # KLE wraps to the cluster's left edge, not to 0
    return keys


# ── Emitting the C macro block ───────────────────────────────────────────────

def emit_c(keys) -> str:
    out = ["/* Physical layout. Generated by tools/keyboard/kle_to_layout.py — edit the",
           " * KLE source rather than these numbers. Hundredths of a key unit. */",
           "#define LAYOUT_GEOMETRY \\"]
    for k in keys:
        if k['rot']:
            line = (f"    KB_KEY_R({k['row']},{k['col']}, {k['x']:>4},{k['y']:>4}, "
                    f"{k['w']:>3},{k['h']:>3}, {k['rot']:>4}, {k['rx']:>4},{k['ry']:>4})")
        elif k['w'] != 100 or k['h'] != 100:
            line = (f"    KB_KEY_S({k['row']},{k['col']}, {k['x']:>4},{k['y']:>4}, "
                    f"{k['w']:>3},{k['h']:>3})")
        else:
            line = f"    KB_KEY({k['row']},{k['col']}, {k['x']:>4},{k['y']:>4})"
        out.append(line + " \\")
    out[-1] = out[-1][:-2].rstrip()       # drop the trailing backslash
    return "\n".join(out) + "\n"


# ── Reading a header back out ────────────────────────────────────────────────

_MACRO = re.compile(r'KB_KEY(_S|_R)?\s*\(([^)]*)\)')


def parse_header(text: str):
    block = text.split('#define LAYOUT_GEOMETRY', 1)
    if len(block) != 2:
        raise SystemExit("error: no #define LAYOUT_GEOMETRY in that file")
    keys = []
    for kind, args in _MACRO.findall(block[1]):
        n = [int(a.strip()) for a in args.split(',')]
        k = dict(row=n[0], col=n[1], x=n[2], y=n[3],
                 w=100, h=100, rot=0, rx=0, ry=0)
        if kind == '_S':
            k.update(w=n[4], h=n[5])
        elif kind == '_R':
            k.update(w=n[4], h=n[5], rot=n[6], rx=n[7], ry=n[8])
        keys.append(k)
    return keys


def emit_kle(keys) -> str:
    """Geometry -> KLE raw data.

    KLE's model is a cursor, not absolute placement: y advances by 1 at the
    start of every row, x resets to the cluster's left edge, and {x:n}/{y:n}
    are *deltas* applied to that cursor. So the only safe way to emit is to
    simulate the exact same cursor the parser above implements and write the
    deltas needed to steer it. Getting this wrong is silent — the numbers look
    plausible and every key lands a little further out than the last.

    Keys are grouped into KLE rows by (rotation cluster, y) so the output reads
    like something a human laid out rather than one row per key.
    """
    groups = {}
    for k in keys:
        groups.setdefault((k['rot'], k['rx'], k['ry'], k['y']), []).append(k)

    rows = []
    cur_y = None
    for key in sorted(groups, key=lambda t: (t[3], t[0])):
        rot, rx, ry, y = key
        members = sorted(groups[key], key=lambda k: k['x'])
        props = {}

        if rot:
            # A rotation cluster snaps the cursor to (rx, ry) before offsets.
            props.update(r=rot, rx=rx / 100.0, ry=ry / 100.0)
            cur_x, base_y = rx, ry
        else:
            cur_x = 0
            base_y = (0 if cur_y is None else cur_y + 100)

        dy = (y - base_y) / 100.0
        if dy:
            props['y'] = dy
        cur_y = y

        row = []
        first = True
        for k in members:
            p = dict(props) if first else {}
            first = False
            dx = (k['x'] - cur_x) / 100.0
            if dx:
                p['x'] = dx
            if k['w'] != 100:
                p['w'] = k['w'] / 100.0
            if k['h'] != 100:
                p['h'] = k['h'] / 100.0
            if p:
                row.append(p)
            row.append(f"{k['row']},{k['col']}")
            cur_x = k['x'] + k['w']
        rows.append(row)

    body = ",\n".join(json.dumps(r) for r in rows)
    return "[\n" + body + "\n]\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("file", help="KLE raw data file, or a keyboard.h with --to-kle")
    ap.add_argument("--to-kle", action="store_true",
                    help="reverse: read LAYOUT_GEOMETRY from a header, print KLE raw data")
    ap.add_argument("-o", "--output", help="write here instead of stdout")
    a = ap.parse_args()

    text = open(a.file).read()
    if a.to_kle:
        result = emit_kle(parse_header(text))
    else:
        keys = parse_kle(_loads_lenient(text))
        if not keys:
            raise SystemExit("error: no keys with a \"row,col\" top-left legend found")
        print(f"// {len(keys)} keys", file=sys.stderr)
        result = emit_c(keys)

    if a.output:
        open(a.output, "w").write(result)
        print(f"wrote {a.output}", file=sys.stderr)
    else:
        sys.stdout.write(result)
    return 0


if __name__ == "__main__":
    sys.exit(main())
