#!/usr/bin/env python3
"""
build_web_html.py — regenerate include/web_html.h from standalone HTML files.

The web UI is embedded in the firmware as C string literals in
include/web_html.h (LOGIN_HTML and MAIN_HTML), which web.cpp #includes. This
script rebuilds that header from standalone .html files so you never hand-edit
the escaped literals.

USAGE
-----
  # regenerate MAIN_HTML from NetHID.html (LOGIN_HTML left untouched):
  python3 tools/build_web_html.py --main NetHID.html

  # regenerate both:
  python3 tools/build_web_html.py --main NetHID.html --login Login.html

  # custom output path:
  python3 tools/build_web_html.py --main NetHID.html -o include/web_html.h

If a literal's source HTML isn't supplied, that literal is preserved as-is from
the existing header (so you can update just MAIN_HTML without touching LOGIN).
"""

import argparse
import os
import sys

HEADER_TOP = """\
// ============================================================
//  web_html.h  —  Embedded web UI markup for NetHID
//
//  Holds the HTML served by web.cpp as C string literals
//  (LOGIN_HTML and MAIN_HTML). GENERATED by tools/build_web_html.py from
//  standalone .html files. Do NOT hand-edit the escaped literals.
//
//  Workflow:
//    1. python3 tools/cstring_to_html.py include/web_html.h -n MAIN_HTML -o NetHID.html
//    2. edit NetHID.html, test in a browser
//    3. python3 tools/build_web_html.py --main NetHID.html
//    4. rebuild + flash
// ============================================================
#pragma once
"""


def escape_line(line: str) -> str:
    line = line.replace('\\', '\\\\')
    line = line.replace('"', '\\"')
    line = line.replace('\t', '  ')
    return line


def html_to_literal(html: str, var_name: str) -> str:
    html = html.replace('\r\n', '\n').replace('\r', '\n')
    lines = html.split('\n')
    if lines and lines[-1] == '':
        lines.pop()
    out = [f'static const char {var_name}[] =']
    for ln in lines:
        out.append(f'"{escape_line(ln)}\\n"')
    out[-1] = out[-1] + ';'
    return '\n'.join(out)


def extract_existing(header_text: str, var_name: str):
    """Return the existing literal block for var_name from the header, or None."""
    lines = header_text.split('\n')
    try:
        start = next(i for i, l in enumerate(lines)
                     if l.startswith(f'static const char {var_name}[]'))
    except StopIteration:
        return None
    end = next(i for i in range(start + 1, len(lines))
               if lines[i].rstrip().endswith('";'))
    return '\n'.join(lines[start:end + 1])


def extract_block(header_text: str, begin: str, end: str):
    """Return the text between begin/end marker lines (inclusive), or None."""
    lines = header_text.split('\n')
    try:
        s = next(i for i, l in enumerate(lines) if l.strip() == begin)
        e = next(i for i in range(s + 1, len(lines)) if lines[i].strip() == end)
    except StopIteration:
        return None
    return '\n'.join(lines[s:e + 1])


import re
_TAB_OPEN = re.compile(r'^\s*<!--@@TAB (\w+)@@-->\s*$')
_TAB_CLOSE = re.compile(r'^\s*<!--@@ENDTAB@@-->\s*$')


def split_main(html: str):
    """Split MAIN HTML into (head_lines, [(id, body_lines)...], footer_lines)
    using <!--@@TAB id@@--> / <!--@@ENDTAB@@--> marker lines (which are dropped).
    head = before the first @@TAB; footer = after the last @@ENDTAB."""
    html = html.replace('\r\n', '\n').replace('\r', '\n')
    head, footer, tabs = [], [], []
    state, cur_id, cur = 'head', None, []
    for ln in html.split('\n'):
        if _TAB_OPEN.match(ln):
            # Starting a tab: anything accumulated as "footer" so far must have
            # been only blank lines between panels.
            if any(x.strip() for x in footer):
                raise SystemExit(f"error: content between tabs: {footer!r}")
            footer = []
            cur_id = _TAB_OPEN.match(ln).group(1); cur = []; state = 'tab'; continue
        if _TAB_CLOSE.match(ln):
            tabs.append((cur_id, cur)); cur_id, cur = None, []; state = 'tail'; continue
        if state == 'head':
            head.append(ln)
        elif state == 'tab':
            cur.append(ln)
        else:                       # 'tail' — provisionally footer (reset if a new tab opens)
            footer.append(ln)
    if not tabs:
        raise SystemExit("error: no @@TAB markers found in MAIN html")
    return head, tabs, footer


def main_fragments_literal(html: str) -> str:
    head, tabs, footer = split_main(html)
    parts = ["// @@MAIN_BEGIN@@"]
    parts.append(html_to_literal('\n'.join(head), 'MAIN_HEAD'))
    for tid, body in tabs:
        parts.append(html_to_literal('\n'.join(body), f'MAIN_TAB_{tid}'))
    parts.append(html_to_literal('\n'.join(footer), 'MAIN_FOOTER'))
    parts.append("typedef struct { const char *id; const char *html; } main_tab_t;")
    parts.append("static const main_tab_t MAIN_TABS[] = {")
    for tid, _ in tabs:
        parts.append(f'    {{ "{tid}", MAIN_TAB_{tid} }},')
    parts.append("};")
    parts.append("static const int MAIN_TAB_COUNT = (int)(sizeof(MAIN_TABS)/sizeof(MAIN_TABS[0]));")
    parts.append("// @@MAIN_END@@")
    return '\n'.join(parts)


def main() -> int:
    ap = argparse.ArgumentParser(description="Regenerate web_html.h from HTML files.")
    ap.add_argument("--main", help="HTML file for MAIN (split into tab fragments)")
    ap.add_argument("--login", help="HTML file for LOGIN_HTML")
    ap.add_argument("--irdb", help="HTML file for IRDB_HTML (served at /irdb)")
    ap.add_argument("--learn", help="HTML file for LEARN_HTML (served at /learn)")
    ap.add_argument("-o", "--out", default="include/web_html.h",
                    help="Output header path (default: include/web_html.h)")
    args = ap.parse_args()

    if not (args.main or args.login or args.irdb or args.learn):
        print("error: supply at least one of --main / --login / --irdb / --learn", file=sys.stderr)
        return 1

    existing = ""
    if os.path.exists(args.out):
        with open(args.out, "r", encoding="utf-8") as f:
            existing = f.read()

    # LOGIN_HTML — single literal (from file or preserved from existing header).
    if args.login:
        with open(args.login, "r", encoding="utf-8") as f:
            login_lit = html_to_literal(f.read(), "LOGIN_HTML")
    else:
        login_lit = extract_existing(existing, "LOGIN_HTML")
        if login_lit is None:
            print(f"error: no source for LOGIN_HTML and none in {args.out}", file=sys.stderr)
            return 1

    # IRDB_HTML — single literal for the /irdb page (from file or preserved).
    if args.irdb:
        with open(args.irdb, "r", encoding="utf-8") as f:
            irdb_lit = html_to_literal(f.read(), "IRDB_HTML")
    else:
        irdb_lit = extract_existing(existing, "IRDB_HTML")
        if irdb_lit is None:
            print(f"error: no source for IRDB_HTML and none in {args.out}", file=sys.stderr)
            return 1

    # LEARN_HTML — single literal for the /learn page (from file or preserved).
    if args.learn:
        with open(args.learn, "r", encoding="utf-8") as f:
            learn_lit = html_to_literal(f.read(), "LEARN_HTML")
    else:
        learn_lit = extract_existing(existing, "LEARN_HTML")
        if learn_lit is None:
            print(f"error: no source for LEARN_HTML and none in {args.out}", file=sys.stderr)
            return 1

    # MAIN — split into HEAD / per-tab / FOOTER + registry (from file or preserved).
    if args.main:
        with open(args.main, "r", encoding="utf-8") as f:
            main_block = main_fragments_literal(f.read())
    else:
        main_block = extract_block(existing, "// @@MAIN_BEGIN@@", "// @@MAIN_END@@")
        if main_block is None:
            print(f"error: no source for MAIN and none in {args.out}", file=sys.stderr)
            return 1

    out = (HEADER_TOP + "\n" + login_lit + "\n\n" + irdb_lit + "\n\n"
           + learn_lit + "\n\n" + main_block + "\n")
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"wrote {args.out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
