#!/usr/bin/env python3
"""Embed a TLS server certificate + private key into a C header.

mbedTLS parses PEM from a NUL-terminated buffer and the length it is given must
*include* that terminating NUL — so the generated SERVER_*_LEN macros use
sizeof() (which counts the implicit NUL of a string literal).

Usage:
    python3 tools/gen_cert_header.py --cert certs/server.crt \
                                     --key  certs/server.key \
                                     -o include/server_cert.h

The cert file may be a full chain (leaf first, then intermediates); mbedTLS
accepts multiple concatenated PEM blocks. Keep the matching CA root installed in
your browsers (mkcert does this automatically; for a public cert it is already
trusted).
"""
import argparse, sys, os, hashlib, datetime

def pem_to_literal(text, name):
    # Normalise CRLF -> LF, ensure trailing newline, emit one C string per line.
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    if not text.endswith("\n"):
        text += "\n"
    lines = text.split("\n")
    if lines and lines[-1] == "":
        lines = lines[:-1]
    out = [f"static const char {name}[] ="]
    for ln in lines:
        esc = ln.replace("\\", "\\\\").replace('"', '\\"')
        out.append(f'    "{esc}\\n"')
    out[-1] += ";"
    return "\n".join(out)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cert", required=True, help="server certificate (PEM, leaf or full chain)")
    ap.add_argument("--key",  required=True, help="server private key (PEM)")
    ap.add_argument("-o", "--out", default="include/server_cert.h")
    args = ap.parse_args()

    for f in (args.cert, args.key):
        if not os.path.isfile(f):
            print(f"error: not found: {f}", file=sys.stderr); return 1

    cert = open(args.cert, "r", encoding="utf-8").read()
    key  = open(args.key,  "r", encoding="utf-8").read()
    if "BEGIN CERTIFICATE" not in cert:
        print("error: --cert is not a PEM certificate", file=sys.stderr); return 1
    if "PRIVATE KEY" not in key:
        print("error: --key is not a PEM private key", file=sys.stderr); return 1

    fp = hashlib.sha256(cert.encode()).hexdigest()[:16]
    hdr = f"""// server_cert.h — GENERATED by tools/gen_cert_header.py. DO NOT EDIT.
// cert: {os.path.basename(args.cert)}   key: {os.path.basename(args.key)}
// sha256(cert)[:16]: {fp}   generated: {datetime.datetime.now().isoformat(timespec='seconds')}
//
// Only included when ENABLE_HTTPS. Treat this file as a secret (it holds the
// private key) and keep it out of version control alongside env.h.
#pragma once

{pem_to_literal(cert, "SERVER_CERT")}

{pem_to_literal(key, "SERVER_KEY")}

// Lengths INCLUDE the terminating NUL, as mbedTLS PEM parsing requires.
#define SERVER_CERT_LEN  (sizeof(SERVER_CERT))
#define SERVER_KEY_LEN   (sizeof(SERVER_KEY))
"""
    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(hdr)
    print(f"wrote {args.out}  (cert {len(cert)} B, key {len(key)} B, fp {fp})")
    return 0

if __name__ == "__main__":
    sys.exit(main())
