#pragma once
/*
 * auth_store.h — runtime override for the compiled-in login passwords.
 *
 * WHY IT FORGETS ITSELF ON A REFLASH
 * ----------------------------------
 * A password you can change from the web UI is a password you can forget, and
 * a keyboard has no "reset" hole. So the stored record carries the build id of
 * the firmware that wrote it (NETHID_BUILD_ID, regenerated by CMake on every
 * build) and is ignored when the running firmware reports a different one.
 *
 * Flashing any freshly built firmware therefore returns the device to the
 * passwords in env.h. That is the documented recovery path, and it is why this
 * is safe to expose at all.
 *
 * Nothing is erased at boot — the stale sector is simply not believed, and is
 * overwritten the next time a password is set. A firmware downgrade back to the
 * exact image that wrote the record would honour it again; only the id matters,
 * not which build is newer.
 *
 * WHY IT IS NOT HASHED
 * --------------------
 * Login is challenge-response: the device computes HMAC-SHA256 keyed by the
 * password, so it must hold the password itself, not a digest of it. The
 * override is stored in plaintext in flash — exactly as the compiled password
 * already sits in plaintext in the firmware image, so anyone who can read flash
 * could read the password before this existed too. This adds no exposure, but
 * it does not add protection either: flash is not a secret store.
 */
#include <stdint.h>
#include <stdbool.h>

#ifndef ENABLE_PASSWORD_STORE
#define ENABLE_PASSWORD_STORE 0
#endif

/* Longest password that can be stored. The compiled ones are not limited by
 * this — only overrides are. */
#define AUTH_PW_MAX 63

/* Users that can have an override. Overrides are indexed by position in
 * USER_LIST, so this only needs to cover the users a firmware defines. */
#define AUTH_STORE_MAX_USERS 8

/* Load the stored overrides, if the record is present, intact, and was written
 * by this firmware. Call once, before auth_init(). */
void auth_store_init(void);

/* The override for user `idx`, or NULL when that user has none (so the caller
 * falls back to the compiled password). */
const char *auth_store_password(int idx);

/* Set (or with NULL/"" clear) the override for user `idx` and queue a flash
 * write. Returns false if idx is out of range or the password is too long.
 *
 * The write itself happens in auth_store_commit_poll() on core 0: a flash erase
 * parks the other core, which must not happen inside a network callback. */
bool auth_store_set(int idx, const char *password);

/* Whether any override is currently in force, and whether one is persisted in
 * flash for this firmware. `any` true with `stored` false is a change that has
 * not reached flash yet; a record that parses but holds no overrides reports
 * false for both, because it is indistinguishable from having no record. */
bool auth_store_any(void);
bool auth_store_stored(void);
bool auth_store_save_pending(void);

/* Run from the main loop on core 0. Performs a queued write. */
void auth_store_commit_poll(void);

/* The running firmware's build id, for display. Never a secret — it identifies
 * an image, not its contents. */
uint32_t    auth_store_build_id(void);
const char *auth_store_build_id_str(void);
