# build_id.cmake — write a value that differs for every build.
#
# Run as a script (cmake -DOUT=... -P) from a custom target that has no outputs,
# so it re-runs on every build rather than only on reconfigure.
#
# The password store records the build id it was written by and is discarded
# when the running firmware reports a different one. That is what makes flashing
# firmware reset a forgotten web password: the id is regenerated here, so any
# image you build and flash disowns whatever the previous one stored.
#
# Only rewriting the file when the value changes is NOT what we want — the value
# must change every time. The write is also what triggers the recompile, so a
# build that changes nothing else still relinks. That is the cost of the
# guarantee, and it is a few seconds on an incremental build.

string(TIMESTAMP _ts "%Y%m%d%H%M%S" UTC)

# A sequence number carried forward from the previous header, so the id is
# guaranteed to differ from the one before it in this build directory.
#
# The timestamp has one-second resolution and string(RANDOM) is seeded from the
# clock, so two builds inside the same second could produce the SAME id from
# both — and an identical id is not a cosmetic collision: the next firmware
# would honour the previous one's stored password, which is the single thing
# this file exists to prevent. A counter cannot collide with itself.
set(_seq 0)
if(EXISTS "${OUT}")
    file(READ "${OUT}" _prev)
    if(_prev MATCHES "#define NETHID_BUILD_SEQ ([0-9]+)")
        math(EXPR _seq "${CMAKE_MATCH_1} + 1")
    endif()
endif()

string(RANDOM LENGTH 8 ALPHABET "0123456789abcdef" _rnd)

string(MD5 _hash "${_ts}-${_seq}-${_rnd}")
string(SUBSTRING "${_hash}" 0 8 _id)

file(WRITE "${OUT}"
"/* Generated by cmake/build_id.cmake on every build. Do not edit, do not commit. */\n"
"#pragma once\n"
"#define NETHID_BUILD_ID 0x${_id}u\n"
"#define NETHID_BUILD_ID_STR \"${_id}\"\n"
"#define NETHID_BUILD_TIME \"${_ts}\"\n"
"#define NETHID_BUILD_SEQ ${_seq}\n")
